# tasks file
---
- name: create (download) directory
  ansible.builtin.file:
    path: "{{ maven_downloads_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - maven
    - maven-download

- name: download
  ansible.builtin.get_url:
    url: "http://apache.cs.uu.nl/maven/maven-{{ maven_version.split('.')[0] }}/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
    dest: "{{ maven_downloads_path }}/apache-maven-{{ maven_version }}-bin.tar.gz"
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
    - maven
    - maven-downloads

- name: install
  ansible.builtin.unarchive:
    src: "{{ maven_downloads_path }}/apache-maven-{{ maven_version }}-bin.tar.gz"
    dest: "{{ maven_install_prefix }}"
    creates: "{{ maven_install_prefix }}/apache-maven-{{ maven_version }}"
    copy: false
  tags:
    - configuration
    - maven
    - maven-install

- name: verify
  ansible.builtin.command: >
    {{ maven_install_prefix }}/apache-maven-{{ maven_version }}/bin/mvn -version
  changed_when: false
  tags:
    - configuration
    - maven
    - maven-install
    - maven-install-verify
